"""
This type stub file was generated by pyright.
"""

__all__ = ("create_connections", "get_connection_settings", "InvalidSettingsError")
MONGODB_CONF_VARS = ...
class InvalidSettingsError(Exception):
    ...


def get_connection_settings(config): # -> list[Any] | dict[Any, Any]:
    """
    Given a config dict, return a sanitized dict of MongoDB connection
    settings that we can then use to establish connections. For new
    applications, settings should exist in a "MONGODB_SETTINGS" key, but
    for backward compactibility we also support several config keys
    prefixed by "MONGODB_", e.g. "MONGODB_HOST", "MONGODB_PORT", etc.
    """
    ...

def create_connections(config): # -> dict[Any, Any]:
    """
    Given Flask application's config dict, extract relevant config vars
    out of it and establish MongoEngine connection(s) based on them.
    """
    ...

