"""
This type stub file was generated by pyright.
"""

MongoEngineJSONEncoder = ...
def override_json_encoder(app): # -> None:
    """
    A function to dynamically create a new MongoEngineJSONEncoder class
    based upon a custom base class.
    This function allows us to combine MongoEngine serialization with
    any changes to Flask's JSONEncoder which a user may have made
    prior to calling init_app.

    NOTE: This does not cover situations where users override
    an instance's json_encoder after calling init_app.
    """
    ...

