"""
This type stub file was generated by pyright.
"""

from flask_debugtoolbar.panels import DebugPanel

package_loader = ...
class MongoDebugPanel(DebugPanel):
    """Panel that shows information about MongoDB operations (including stack)

    Adapted from https://github.com/hmarr/django-debug-toolbar-mongo
    """
    name = ...
    has_content = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def process_request(self, request): # -> None:
        ...
    
    def nav_title(self): # -> Literal['MongoDB']:
        ...
    
    def nav_subtitle(self): # -> str:
        ...
    
    def title(self): # -> Literal['MongoDB Operations']:
        ...
    
    def url(self): # -> Literal['']:
        ...
    
    def content(self):
        ...
    


