"""
This type stub file was generated by pyright.
"""

import sys
from flask.sessions import SessionInterface, SessionMixin
from werkzeug.datastructures import CallbackDict

__all__ = ("MongoEngineSession", "MongoEngineSessionInterface")
if sys.version_info >= (3, 0):
    basestring = str
class MongoEngineSession(CallbackDict, SessionMixin):
    def __init__(self, initial=..., sid=...) -> None:
        ...
    


class MongoEngineSessionInterface(SessionInterface):
    """SessionInterface for mongoengine"""
    def __init__(self, db, collection=...) -> None:
        """
        The MongoSessionInterface

        :param db: The app's db eg: MongoEngine()
        :param collection: The session collection name defaults to "session"
        """
        class DBSession(db.Document):
            ...
        
        
    
    def get_expiration_time(self, app, session): # -> timedelta:
        ...
    
    def open_session(self, app, request): # -> MongoEngineSession:
        ...
    
    def save_session(self, app, session, response): # -> None:
        ...
    


