"""
This type stub file was generated by pyright.
"""

from mongoengine.base import BaseField

__all__ = "WtfBaseField"
class WtfBaseField(BaseField):
    """
    Extension wrapper class for mongoengine BaseField.

    This enables flask-mongoengine  wtf to extend the
    number of field parameters, and settings on behalf
    of document model form generator for WTForm.

    @param validators:  wtf model form field validators.
    @param filters:     wtf model form field filters.
    """
    def __init__(self, validators=..., filters=..., **kwargs) -> None:
        ...
    


