"""
This type stub file was generated by pyright.
"""

from flask_wtf import FlaskForm

class ModelForm(FlaskForm):
    """A WTForms mongoengine model form"""
    def __init__(self, formdata=..., **kwargs) -> None:
        ...
    
    def save(self, commit=..., **kwargs):
        ...
    


